# ./docker-compose.yml

web:
  build: .
  dockerfile: Dockerfile # That's our Dockerfile path
  env_file: .env # Set environment variables from an `.env` file, if needed
  command: mix phoenix.server # Start the server if no other command is specified
  environment:
    - MIX_ENV=dev # That's the environment mode, you know
    - PORT=4000
  volumes:
    - .:/app # Here we're mounting our project's root directory inside the container
  ports:
    - "4000:4000"

test:
  image: phoenixbootstrap_web # We're just using the already built `web` image here
  env_file: .env
  command: mix test # Run the entire test suite if no other command is specified
  environment:
    - MIX_ENV=test # That's key
    - PORT=4001
  volumes_from:
    - web
